# Generated by Django 2.2.3 on 2019-07-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('urls', models.CharField(max_length=256)),
                ('self_submission', models.BooleanField()),
                ('is_part_of_larger_attack', models.BooleanField()),
            ],
        ),
    ]
