# Generated by Django 2.2.3 on 2019-07-30 06:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None),
        ),
    ]
